### ISSUE TITLE
Testing issues from mobile

### ISSUE THREAD

**Issue by textpotential** [hlab-repo/hlab-embedded#1]
@timothybeal I can mention u in this issue. 

- Supports
- Markdown
- Which is rad

**Comment by textpotential** [comment]
Now we can have full conversations around this particular issue.

**Comment by textpotential** [comment]
@jobarber this is an issue. I wonder if u get a notification.

**Comment by timothybeal** [comment]
Testing so so rad

**Comment by jobarber** [comment]
I see the issue!

**Comment by textpotential** [comment]
We could also link this to slack for notifications and such and u can add issues from slack too. So then I wouldn't have to mention @jobarber and @timothybeal for them to see this comment.

**Comment by jobarber** [comment]
Excellent. Slack is fine as well. Thanks for setting this up!

**Comment by jobarber** [comment]
Testing phone app!
