### ISSUE TITLE
Go to hell

### ISSUE THREAD

**Issue by timothybeal** [hlab-repo/hlab-embedded#4]
Do it @textpotential @jobarber

**Comment by textpotential** [comment]
Would love to see this work for us, @jobarber and @timothybeal

**Comment by jobarber** [comment]
Thanks for your help with this, @textpotential.

**Comment by timothybeal** [comment]
Me too!

**Comment by textpotential** [comment]
The notifications tab on the app is really useful. It shows you unread notifications.
