### ISSUE TITLE
Share videos from lens

### ISSUE THREAD

**Issue by textpotential** [hlab-repo/hlab-embedded#7]
I figured out how to record my using the lens an how to get videos off of the lens. So, i will add some to our documentation.

**Comment by timothybeal** [comment]
How’d you do it? Did you need to use the windows pc?


Timothy Beal
Florence Harkness Professor of Religion
Chair, Department of Religious Studies
Director, h.lab
Case Western Reserve University

**Comment by textpotential** [comment]
Yep. When plugged into the pc, the lens is like an external drive when
powered on. Saves recordings in picture file it seems. Although it only
seems to be working for my personal Microsoft account not my case account.
So still experimenting.

M

**Comment by textpotential** [comment]
Ok, i figured it out. I shared a video via google drive in our case.edu accounts. Let me know if you can see it. Closing this issue for now, since we know how to do this. 

Without PC, we should be able to use OneDrive to share these media, but they are huge files so, likely best to do this way using the PC. Plus, then we can remove videos from the lens cause not much storage there.

**Comment by textpotential** [comment]
@timothybeal do you think it would be useful for us to develop documentation on how to do things like this with the lens? 

Should I work up steps on how to record and then share? 

Btw, had to run windows updates on both the machine and the lens. Geez!
